/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/currencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MoneyController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["UsersController_updateMe"];
        trace?: never;
    };
    "/family": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FamilyController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["FamilyController_update"];
        trace?: never;
    };
    "/family/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["FamilyController_removeMember"];
        options?: never;
        head?: never;
        patch: operations["FamilyController_updateMember"];
        trace?: never;
    };
    "/family/leave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["FamilyController_leave"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/family/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FamilyController_listInvites"];
        put?: never;
        post: operations["FamilyController_createInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/family/invites/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["FamilyController_revokeInvite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites/incoming": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["InvitesController_incoming"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["InvitesController_preview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["InvitesController_acceptByToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites/{id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["InvitesController_acceptById"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites/{id}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["InvitesController_decline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AccountsController_list"];
        put?: never;
        post: operations["AccountsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AccountsController_get"];
        put?: never;
        post?: never;
        delete: operations["AccountsController_remove"];
        options?: never;
        head?: never;
        patch: operations["AccountsController_update"];
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CategoriesController_list"];
        put?: never;
        post: operations["CategoriesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["CategoriesController_remove"];
        options?: never;
        head?: never;
        patch: operations["CategoriesController_update"];
        trace?: never;
    };
    "/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TransactionsController_list"];
        put?: never;
        post: operations["TransactionsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TransactionsController_get"];
        put: operations["TransactionsController_replace"];
        post?: never;
        delete: operations["TransactionsController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exchange-rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ExchangeRatesController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exchange-rates/convert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ExchangeRatesController_convert"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ReportsController_balance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ReportsController_byCategory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/monthly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ReportsController_monthly"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ReportsController_byMember"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budgets/{month}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BudgetsController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budgets/{month}/{categoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["BudgetsController_set"];
        post?: never;
        delete: operations["BudgetsController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budgets/{month}/copy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["BudgetsController_copy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recurring-payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RecurringController_list"];
        put?: never;
        post: operations["RecurringController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recurring-payments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["RecurringController_replace"];
        post?: never;
        delete: operations["RecurringController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recurring-payments/{id}/pay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RecurringController_pay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recurring-payments/{id}/skip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RecurringController_skip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GoalsController_list"];
        put?: never;
        post: operations["GoalsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["GoalsController_remove"];
        options?: never;
        head?: never;
        patch: operations["GoalsController_update"];
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["NotificationsController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["NotificationsController_updateSettings"];
        trace?: never;
    };
    "/notifications/vk/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["NotificationsController_startLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/vk/link/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["NotificationsController_completeLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/vk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["NotificationsController_unlink"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/vk/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["NotificationsController_sendTest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthDto: {
            /** @enum {string} */
            status: "ok";
        };
        CurrencyDto: {
            /** @example RUB */
            code: string;
            /** @example Российский рубль */
            name: string;
            /** @example ₽ */
            symbol: string;
            /**
             * @description Знаков после запятой
             * @example 2
             */
            decimals: number;
        };
        RegisterDto: {
            /**
             * Format: email
             * @example anna@example.com
             */
            email: string;
            password: string;
            /** @example Анна */
            name: string;
        };
        UserDto: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            name: string;
            /** Format: date-time */
            createdAt: string;
        };
        AuthResponseDto: {
            /** @description JWT для заголовка Authorization: Bearer */
            accessToken: string;
            /** @description Время жизни access-токена, секунды */
            expiresIn: number;
            /** @description Одноразовый: после /auth/refresh заменяется новым */
            refreshToken: string;
            user: components["schemas"]["UserDto"];
        };
        LoginDto: {
            /**
             * Format: email
             * @example anna@example.com
             */
            email: string;
            password: string;
        };
        RefreshDto: {
            refreshToken: string;
        };
        TokensDto: {
            /** @description JWT для заголовка Authorization: Bearer */
            accessToken: string;
            /** @description Время жизни access-токена, секунды */
            expiresIn: number;
            /** @description Одноразовый: после /auth/refresh заменяется новым */
            refreshToken: string;
        };
        UpdateProfileDto: {
            name?: string;
        };
        /**
         * @description Роль текущего пользователя
         * @enum {string}
         */
        FamilyRole: "owner" | "member";
        FamilyMemberDto: {
            /** Format: uuid */
            userId: string;
            name: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["FamilyRole"];
            /** Format: date-time */
            joinedAt: string;
        };
        FamilyDto: {
            /** Format: uuid */
            id: string;
            /** @example Семья Ивановых */
            name: string;
            /**
             * @description Валюта отчётов, общего баланса и бюджетов
             * @example RUB
             */
            baseCurrency: string;
            /** @description Роль текущего пользователя */
            role: components["schemas"]["FamilyRole"];
            members: components["schemas"]["FamilyMemberDto"][];
        };
        UpdateFamilyDto: {
            name?: string;
            /**
             * @example RUB
             * @enum {string}
             */
            baseCurrency?: "RUB" | "USD" | "EUR" | "CNY" | "GBP" | "JPY" | "KZT" | "BYN" | "TRY" | "AMD" | "GEL" | "AED";
        };
        UpdateMemberDto: {
            role: components["schemas"]["FamilyRole"];
        };
        InviteDto: {
            /** Format: uuid */
            id: string;
            /**
             * Format: email
             * @description Принять может только пользователь с этим email
             */
            email: string | null;
            /** @description Кто пригласил */
            invitedBy: string;
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            createdAt: string;
        };
        CreateInviteDto: {
            /**
             * Format: email
             * @description Без email приглашение принимается по ссылке кем угодно
             */
            email?: string;
        };
        CreatedInviteDto: {
            /** Format: uuid */
            id: string;
            /**
             * Format: email
             * @description Принять может только пользователь с этим email
             */
            email: string | null;
            /** @description Кто пригласил */
            invitedBy: string;
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            createdAt: string;
            /** @description Секрет для ссылки приглашения. Показывается один раз, в базе хранится только хеш */
            token: string;
        };
        IncomingInviteDto: {
            /** Format: uuid */
            id: string;
            /**
             * Format: email
             * @description Принять может только пользователь с этим email
             */
            email: string | null;
            /** @description Кто пригласил */
            invitedBy: string;
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            createdAt: string;
            familyName: string;
        };
        InviteTokenDto: {
            token: string;
        };
        /** @enum {string} */
        AccountType: "cash" | "card" | "deposit";
        /**
         * @description Что семья видит по личному счёту: full — остаток и операции, summary — остаток и итоги
         * @enum {string}
         */
        AccountVisibility: "full" | "summary";
        AccountDto: {
            /** Format: uuid */
            id: string;
            /** @example Карта Тинькофф */
            name: string;
            type: components["schemas"]["AccountType"];
            /** @example RUB */
            currency: string;
            /**
             * Format: uuid
             * @description Владелец личного счёта; null — общий счёт семьи
             */
            ownerId: string | null;
            /** @description Что семья видит по личному счёту: full — остаток и операции, summary — остаток и итоги */
            visibility: components["schemas"]["AccountVisibility"];
            /** @description Текущий пользователь может проводить операции */
            canTransact: boolean;
            /** @description Текущий пользователь может менять счёт */
            canManage: boolean;
            /**
             * @description Остаток на момент заведения счёта
             * @example 150000
             */
            initialBalance: string;
            /**
             * @description Текущий остаток с учётом всех операций
             * @example 150000
             */
            balance: string;
            archived: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        CreateAccountDto: {
            /**
             * Format: uuid
             * @description Создаётся клиентом
             */
            id: string;
            name: string;
            type: components["schemas"]["AccountType"];
            /**
             * @example RUB
             * @enum {string}
             */
            currency: "RUB" | "USD" | "EUR" | "CNY" | "GBP" | "JPY" | "KZT" | "BYN" | "TRY" | "AMD" | "GEL" | "AED";
            /**
             * @description По умолчанию 0
             * @example 150000
             */
            initialBalance?: string;
            /** @description Общий счёт семьи (создаёт владелец семьи). По умолчанию личный */
            shared?: boolean;
            /** @description Только для личного счёта, по умолчанию full */
            visibility?: components["schemas"]["AccountVisibility"];
        };
        UpdateAccountDto: {
            name?: string;
            type?: components["schemas"]["AccountType"];
            /** @example 150000 */
            initialBalance?: string;
            /** @description Архивный счёт скрыт из форм */
            archived?: boolean;
            /** @description Только для личного счёта */
            visibility?: components["schemas"]["AccountVisibility"];
        };
        /** @enum {string} */
        CategoryKind: "income" | "expense";
        CategoryDto: {
            /** Format: uuid */
            id: string;
            /** @example Продукты */
            name: string;
            kind: components["schemas"]["CategoryKind"];
            /**
             * Format: uuid
             * @description Родительская категория; вложенность — один уровень
             */
            parentId: string | null;
            archived: boolean;
        };
        CreateCategoryDto: {
            /**
             * Format: uuid
             * @description Создаётся клиентом
             */
            id: string;
            name: string;
            kind: components["schemas"]["CategoryKind"];
            /** Format: uuid */
            parentId?: string | null;
        };
        UpdateCategoryDto: {
            name?: string;
            /**
             * Format: uuid
             * @description null — сделать категорию верхнего уровня
             */
            parentId?: string | null;
            archived?: boolean;
        };
        /** @enum {string} */
        TransactionType: "income" | "expense" | "transfer";
        TransactionDto: {
            /** Format: uuid */
            id: string;
            type: components["schemas"]["TransactionType"];
            /**
             * Format: date
             * @example 2026-09-29
             */
            date: string;
            /**
             * Format: uuid
             * @description Счёт дохода или расхода; для перевода — счёт списания
             */
            accountId: string;
            /**
             * @description Сумма в валюте счёта accountId, > 0. null — перевод со счёта, детализацию которого владелец скрыл
             * @example 150000
             */
            amount: string | null;
            /** Format: uuid */
            categoryId: string | null;
            /**
             * Format: uuid
             * @description Перевод: счёт зачисления
             */
            toAccountId: string | null;
            /**
             * @description Перевод: сумма зачисления в валюте счёта toAccountId. null — не перевод или счёт скрыт
             * @example 150000
             */
            toAmount: string | null;
            comment: string;
            /**
             * Format: uuid
             * @description Автор операции
             */
            authorId: string;
            authorName: string;
            /** @description Текущий пользователь может изменить или удалить операцию */
            canEdit: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        TransactionPageDto: {
            items: components["schemas"]["TransactionDto"][];
            /** @description Всего операций под фильтром */
            total: number;
        };
        CreateTransactionDto: {
            type: components["schemas"]["TransactionType"];
            /**
             * Format: date
             * @example 2026-09-29
             */
            date: string;
            /** Format: uuid */
            accountId: string;
            /**
             * @description Сумма в валюте счёта accountId, > 0
             * @example 150000
             */
            amount: string;
            /**
             * Format: uuid
             * @description Обязательна для дохода и расхода, у перевода её нет
             */
            categoryId?: string | null;
            /**
             * Format: uuid
             * @description Обязателен для перевода
             */
            toAccountId?: string | null;
            /**
             * @description Перевод: сумма зачисления. Обязательна, если валюты счетов разные; при одной валюте равна amount
             * @example 150000
             */
            toAmount?: string | null;
            comment?: string;
            /**
             * Format: uuid
             * @description Создаётся клиентом; повторная отправка не создаёт дубль
             */
            id: string;
        };
        SaveTransactionDto: {
            type: components["schemas"]["TransactionType"];
            /**
             * Format: date
             * @example 2026-09-29
             */
            date: string;
            /** Format: uuid */
            accountId: string;
            /**
             * @description Сумма в валюте счёта accountId, > 0
             * @example 150000
             */
            amount: string;
            /**
             * Format: uuid
             * @description Обязательна для дохода и расхода, у перевода её нет
             */
            categoryId?: string | null;
            /**
             * Format: uuid
             * @description Обязателен для перевода
             */
            toAccountId?: string | null;
            /**
             * @description Перевод: сумма зачисления. Обязательна, если валюты счетов разные; при одной валюте равна amount
             * @example 150000
             */
            toAmount?: string | null;
            comment?: string;
        };
        ExchangeRateDto: {
            /** @example USD */
            currency: string;
            /**
             * @description Сколько рублей стоит 1 единица валюты
             * @example 92.5
             */
            rate: string;
        };
        ConvertResultDto: {
            /**
             * @description Сумма в минимальных единицах валюты to; null — курса нет
             * @example 150000
             */
            amount: string | null;
        };
        AccountBalanceDto: {
            /** Format: uuid */
            accountId: string;
            /** @example USD */
            currency: string;
            /**
             * @description В валюте счёта
             * @example 150000
             */
            balance: string;
            /**
             * @description В основной валюте по текущему курсу; null — курса нет
             * @example 150000
             */
            converted: string | null;
        };
        BalanceReportDto: {
            /**
             * @description Основная валюта семьи
             * @example RUB
             */
            currency: string;
            /** @description Валюты, для которых нет ни одного курса: их суммы в отчёт не вошли */
            missingRates: string[];
            /**
             * @description Сумма остатков в основной валюте
             * @example 150000
             */
            total: string;
            accounts: components["schemas"]["AccountBalanceDto"][];
        };
        CategoryAmountDto: {
            /**
             * Format: uuid
             * @description Категория верхнего уровня; подкатегории включены в неё. null — «Личные (скрыто)»: операции по скрытым счетам других участников одной строкой
             */
            categoryId: string | null;
            name: string;
            /** @example 150000 */
            amount: string;
        };
        CategoryReportDto: {
            /**
             * @description Основная валюта семьи
             * @example RUB
             */
            currency: string;
            /** @description Валюты, для которых нет ни одного курса: их суммы в отчёт не вошли */
            missingRates: string[];
            /** @example 150000 */
            total: string;
            /** @description По убыванию суммы */
            items: components["schemas"]["CategoryAmountDto"][];
        };
        MonthAmountDto: {
            /** @example 2026-09 */
            month: string;
            /** @example 150000 */
            income: string;
            /** @example 150000 */
            expense: string;
        };
        MonthlyReportDto: {
            /**
             * @description Основная валюта семьи
             * @example RUB
             */
            currency: string;
            /** @description Валюты, для которых нет ни одного курса: их суммы в отчёт не вошли */
            missingRates: string[];
            /** @description Все месяцы периода по порядку, включая пустые */
            months: components["schemas"]["MonthAmountDto"][];
        };
        MemberAmountDto: {
            /** Format: uuid */
            userId: string;
            name: string;
            /** @example 150000 */
            income: string;
            /** @example 150000 */
            expense: string;
        };
        MemberReportDto: {
            /**
             * @description Основная валюта семьи
             * @example RUB
             */
            currency: string;
            /** @description Валюты, для которых нет ни одного курса: их суммы в отчёт не вошли */
            missingRates: string[];
            /** @description Доходы и расходы по авторам операций, по убыванию расходов */
            items: components["schemas"]["MemberAmountDto"][];
        };
        BudgetItemDto: {
            /** Format: uuid */
            categoryId: string;
            name: string;
            /**
             * @description Лимит в основной валюте; null — лимита нет
             * @example 150000
             */
            limit: string | null;
            /**
             * @description Потрачено в основной валюте, с подкатегориями. Расходы по скрытым счетам других участников сюда не входят
             * @example 150000
             */
            spent: string;
        };
        BudgetMonthDto: {
            /** @example 2026-09 */
            month: string;
            /**
             * @description Основная валюта семьи
             * @example RUB
             */
            currency: string;
            /** @description Категории с лимитом, затем категории без лимита, но с расходами */
            items: components["schemas"]["BudgetItemDto"][];
            /**
             * @description Сумма лимитов
             * @example 150000
             */
            totalLimit: string;
            /**
             * @description Потрачено в категориях с лимитом
             * @example 150000
             */
            totalSpent: string;
            /**
             * @description Потрачено в категориях без лимита
             * @example 150000
             */
            otherSpent: string;
            /**
             * @description Расходы по скрытым счетам других участников («Личные (скрыто)»)
             * @example 150000
             */
            hiddenSpent: string;
            /** @description Валюты, для которых нет ни одного курса */
            missingRates: string[];
        };
        SetBudgetDto: {
            /**
             * @description Лимит в основной валюте семьи, > 0
             * @example 150000
             */
            amount: string;
        };
        CopyBudgetsDto: {
            /**
             * @description Месяц, из которого копируются лимиты
             * @example 2026-09
             */
            from: string;
        };
        /** @enum {string} */
        RecurrenceFrequency: "weekly" | "monthly" | "yearly";
        RecurringPaymentDto: {
            /** Format: uuid */
            id: string;
            /** @example Аренда квартиры */
            name: string;
            type: components["schemas"]["TransactionType"];
            /** Format: uuid */
            accountId: string;
            /**
             * @description Сумма в валюте счёта accountId. null — перевод со счёта, детализацию которого владелец скрыл
             * @example 150000
             */
            amount: string | null;
            /** Format: uuid */
            categoryId: string | null;
            /** Format: uuid */
            toAccountId: string | null;
            /** @example 150000 */
            toAmount: string | null;
            comment: string;
            frequency: components["schemas"]["RecurrenceFrequency"];
            /** @description Каждые interval недель, месяцев или лет */
            interval: number;
            /**
             * Format: date
             * @description Ближайший непроведённый платёж; null — расписание закончилось
             */
            nextDate: string | null;
            /** Format: date */
            endDate: string | null;
            /** @description За сколько дней до платежа напоминать */
            remindDaysBefore: number;
            /** Format: uuid */
            authorId: string;
            authorName: string;
            /** @description Текущий пользователь может изменить платёж */
            canEdit: boolean;
            /** @description Текущий пользователь может провести или пропустить платёж */
            canPay: boolean;
        };
        CreateRecurringPaymentDto: {
            name: string;
            type: components["schemas"]["TransactionType"];
            /** Format: uuid */
            accountId: string;
            /**
             * @description Сумма в валюте счёта accountId, > 0
             * @example 150000
             */
            amount: string;
            /** Format: uuid */
            categoryId?: string | null;
            /** Format: uuid */
            toAccountId?: string | null;
            /** @example 150000 */
            toAmount?: string | null;
            comment?: string;
            frequency: components["schemas"]["RecurrenceFrequency"];
            /** @default 1 */
            interval: number;
            /**
             * Format: date
             * @description Дата следующего платежа; от неё отсчитываются последующие повторения
             * @example 2026-09-29
             */
            nextDate: string;
            /**
             * Format: date
             * @description Последний день расписания; null — без конца
             */
            endDate?: string | null;
            /** @default 3 */
            remindDaysBefore: number;
            /**
             * Format: uuid
             * @description Создаётся клиентом
             */
            id: string;
        };
        SaveRecurringPaymentDto: {
            name: string;
            type: components["schemas"]["TransactionType"];
            /** Format: uuid */
            accountId: string;
            /**
             * @description Сумма в валюте счёта accountId, > 0
             * @example 150000
             */
            amount: string;
            /** Format: uuid */
            categoryId?: string | null;
            /** Format: uuid */
            toAccountId?: string | null;
            /** @example 150000 */
            toAmount?: string | null;
            comment?: string;
            frequency: components["schemas"]["RecurrenceFrequency"];
            /** @default 1 */
            interval: number;
            /**
             * Format: date
             * @description Дата следующего платежа; от неё отсчитываются последующие повторения
             * @example 2026-09-29
             */
            nextDate: string;
            /**
             * Format: date
             * @description Последний день расписания; null — без конца
             */
            endDate?: string | null;
            /** @default 3 */
            remindDaysBefore: number;
        };
        PayRecurringPaymentDto: {
            /**
             * Format: date
             * @description Текущая nextDate платежа. Если платёж уже сдвинулся (проведён с другого устройства), ответ 409
             * @example 2026-09-29
             */
            occurrence: string;
            /**
             * Format: uuid
             * @description id создаваемой операции (от клиента): повторная отправка не проводит платёж дважды
             */
            transactionId: string;
            /**
             * Format: date
             * @description Дата операции, по умолчанию occurrence
             * @example 2026-09-29
             */
            date?: string;
            /**
             * @description Сумма, если отличается от обычной
             * @example 150000
             */
            amount?: string;
            /**
             * @description Перевод в другую валюту: сумма зачисления
             * @example 150000
             */
            toAmount?: string;
        };
        PaidRecurringPaymentDto: {
            payment: components["schemas"]["RecurringPaymentDto"];
            transaction: components["schemas"]["TransactionDto"];
        };
        SkipRecurringPaymentDto: {
            /**
             * Format: date
             * @description Текущая nextDate платежа. Если платёж уже сдвинулся (проведён с другого устройства), ответ 409
             * @example 2026-09-29
             */
            occurrence: string;
        };
        GoalDto: {
            /** Format: uuid */
            id: string;
            /** @example Отпуск */
            name: string;
            /**
             * @description Валюта цели
             * @example RUB
             */
            currency: string;
            /**
             * @description Сколько нужно накопить, в валюте цели
             * @example 150000
             */
            targetAmount: string;
            /**
             * @description Накоплено в валюте цели: остаток счёта accountId по текущему курсу, а без счёта — savedAmount. null — нет курса валюты счёта
             * @example 150000
             */
            saved: string | null;
            /**
             * @description Накоплено вручную (для цели без счёта)
             * @example 150000
             */
            savedAmount: string;
            /**
             * Format: uuid
             * @description Счёт, остаток которого считается накопленным
             */
            accountId: string | null;
            /** Format: date */
            targetDate: string | null;
            archived: boolean;
            /** Format: uuid */
            authorId: string;
            authorName: string;
            /** @description Текущий пользователь может изменить цель: автор или владелец семьи */
            canEdit: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        CreateGoalDto: {
            /**
             * Format: uuid
             * @description Создаётся клиентом
             */
            id: string;
            name: string;
            /**
             * @example RUB
             * @enum {string}
             */
            currency: "RUB" | "USD" | "EUR" | "CNY" | "GBP" | "JPY" | "KZT" | "BYN" | "TRY" | "AMD" | "GEL" | "AED";
            /**
             * @description > 0
             * @example 150000
             */
            targetAmount: string;
            /**
             * @description По умолчанию 0
             * @example 150000
             */
            savedAmount?: string;
            /** Format: uuid */
            accountId?: string | null;
            /** Format: date */
            targetDate?: string | null;
        };
        UpdateGoalDto: {
            name?: string;
            /** @enum {string} */
            currency?: "RUB" | "USD" | "EUR" | "CNY" | "GBP" | "JPY" | "KZT" | "BYN" | "TRY" | "AMD" | "GEL" | "AED";
            /** @example 150000 */
            targetAmount?: string;
            /** @example 150000 */
            savedAmount?: string;
            /**
             * Format: uuid
             * @description null — отвязать счёт
             */
            accountId?: string | null;
            /** Format: date */
            targetDate?: string | null;
            archived?: boolean;
        };
        VkStatusDto: {
            /** @description Сервер настроен для привязки ВКонтакте */
            available: boolean;
            linked: boolean;
            /** @description Имя в ВК */
            name: string | null;
            /** @description Сообщество может писать пользователю. Если нет — открыть allowMessagesUrl и написать сообществу */
            messagesAllowed: boolean;
            allowMessagesUrl: string | null;
        };
        NotificationSettingsDto: {
            /** @description Регулярные платежи */
            recurring: boolean;
            /** @description Расходы дошли до 80% и 100% лимита */
            budget: boolean;
            /** @description Операции других участников по общим счетам */
            familyTransactions: boolean;
            /** @description Приглашения в семью */
            invites: boolean;
            /** @description Достигнутые цели накоплений */
            goals: boolean;
        };
        NotificationsDto: {
            vk: components["schemas"]["VkStatusDto"];
            settings: components["schemas"]["NotificationSettingsDto"];
        };
        UpdateNotificationSettingsDto: {
            recurring?: boolean;
            budget?: boolean;
            familyTransactions?: boolean;
            invites?: boolean;
            goals?: boolean;
        };
        VkLinkUrlDto: {
            /** @description Адрес VK ID, куда перейти для привязки */
            url: string;
        };
        CompleteVkLinkDto: {
            code: string;
            state: string;
            /** @description device_id из редиректа */
            deviceId: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthDto"];
                };
            };
        };
    };
    MoneyController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrencyDto"][];
                };
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
            /** @description Email уже занят */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
            /** @description Неверный email или пароль */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokensDto"];
                };
            };
            /** @description Токен недействителен или отозван */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
        };
    };
    UsersController_updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
        };
    };
    FamilyController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Семья пользователя */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FamilyDto"];
                };
            };
        };
    };
    FamilyController_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateFamilyDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FamilyDto"];
                };
            };
            /** @description Только владелец семьи */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FamilyController_removeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Участник уходит в свою семью вместе с личными счетами */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Только владелец семьи */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FamilyController_updateMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMemberDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FamilyDto"];
                };
            };
            /** @description Только владелец семьи */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description В семье не останется владельца */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FamilyController_leave: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Новая семья пользователя: личные счета и копия категорий */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FamilyDto"];
                };
            };
            /** @description Пользователь один в семье или последний владелец */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FamilyController_listInvites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Действующие приглашения */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteDto"][];
                };
            };
            /** @description Только владелец семьи */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FamilyController_createInvite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInviteDto"];
            };
        };
        responses: {
            /** @description Приглашение действует 7 дней и принимается один раз */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedInviteDto"];
                };
            };
            /** @description Только владелец семьи */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Пользователь с этим email уже в семье */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FamilyController_revokeInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InvitesController_incoming: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Приглашения на email пользователя */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncomingInviteDto"][];
                };
            };
        };
    };
    InvitesController_preview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteTokenDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncomingInviteDto"];
                };
            };
            /** @description Приглашение на другой email */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Истекло, отозвано или уже принято */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InvitesController_acceptByToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteTokenDto"];
            };
        };
        responses: {
            /** @description Принять по ссылке */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FamilyDto"];
                };
            };
            /** @description Приглашение на другой email */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Истекло, отозвано или уже принято */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Уже в этой семье или в текущей семье есть другие участники */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InvitesController_acceptById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Принять входящее */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FamilyDto"];
                };
            };
            /** @description Истекло, отозвано или уже принято */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Уже в этой семье или в текущей семье есть другие участники */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InvitesController_decline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AccountsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountDto"][];
                };
            };
        };
    };
    AccountsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccountDto"];
            };
        };
        responses: {
            /** @description Повтор с тем же id возвращает уже созданный счёт */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountDto"];
                };
            };
            /** @description id занят другим пользователем */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AccountsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountDto"];
                };
            };
        };
    };
    AccountsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description По счёту есть операции */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AccountsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAccountDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountDto"];
                };
            };
        };
    };
    CategoriesController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryDto"][];
                };
            };
        };
    };
    CategoriesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryDto"];
            };
        };
        responses: {
            /** @description Повтор с тем же id возвращает уже созданную категорию */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryDto"];
                };
            };
            /** @description id занят другим пользователем */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Категория используется в операциях или регулярных платежах либо имеет подкатегории */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCategoryDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryDto"];
                };
            };
        };
    };
    TransactionsController_list: {
        parameters: {
            query?: {
                /** @description С даты включительно */
                from?: string;
                /** @description По дату включительно */
                to?: string;
                type?: components["schemas"]["TransactionType"];
                /** @description Операции по счёту, включая переводы на него */
                accountId?: string;
                /** @description Категория вместе с подкатегориями */
                categoryId?: string;
                /** @description Автор операции */
                authorId?: string;
                /** @description Поиск по комментарию */
                search?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionPageDto"];
                };
            };
        };
    };
    TransactionsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTransactionDto"];
            };
        };
        responses: {
            /** @description Повтор с тем же id возвращает уже созданную операцию */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionDto"];
                };
            };
            /** @description Неверные счёт, категория или суммы */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description id занят другим пользователем */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TransactionsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionDto"];
                };
            };
        };
    };
    TransactionsController_replace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveTransactionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionDto"];
                };
            };
            /** @description Неверные счёт, категория или суммы */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TransactionsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ExchangeRatesController_list: {
        parameters: {
            query?: {
                /** @description По умолчанию — последний известный курс */
                date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExchangeRateDto"][];
                };
            };
        };
    };
    ExchangeRatesController_convert: {
        parameters: {
            query: {
                /** @description По умолчанию — последний известный курс */
                date?: string;
                /** @description Сумма в минимальных единицах валюты from */
                amount: string;
                from: "RUB" | "USD" | "EUR" | "CNY" | "GBP" | "JPY" | "KZT" | "BYN" | "TRY" | "AMD" | "GEL" | "AED";
                to: "RUB" | "USD" | "EUR" | "CNY" | "GBP" | "JPY" | "KZT" | "BYN" | "TRY" | "AMD" | "GEL" | "AED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConvertResultDto"];
                };
            };
        };
    };
    ReportsController_balance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalanceReportDto"];
                };
            };
        };
    };
    ReportsController_byCategory: {
        parameters: {
            query: {
                /** @description С даты включительно */
                from: string;
                /** @description По дату включительно */
                to: string;
                /** @description Только операции этого участника */
                authorId?: string;
                kind: components["schemas"]["CategoryKind"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryReportDto"];
                };
            };
        };
    };
    ReportsController_monthly: {
        parameters: {
            query: {
                /** @description С даты включительно */
                from: string;
                /** @description По дату включительно */
                to: string;
                /** @description Только операции этого участника */
                authorId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyReportDto"];
                };
            };
        };
    };
    ReportsController_byMember: {
        parameters: {
            query: {
                /** @description С даты включительно */
                from: string;
                /** @description По дату включительно */
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberReportDto"];
                };
            };
        };
    };
    BudgetsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                month: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetMonthDto"];
                };
            };
        };
    };
    BudgetsController_set: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                month: string;
                /** @description Категория расходов верхнего уровня */
                categoryId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetBudgetDto"];
            };
        };
        responses: {
            /** @description Бюджет месяца */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetMonthDto"];
                };
            };
            /** @description Категория не расходов или не верхнего уровня */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BudgetsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                month: string;
                /** @description Категория расходов верхнего уровня */
                categoryId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Лимита больше нет (или не было) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BudgetsController_copy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                month: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CopyBudgetsDto"];
            };
        };
        responses: {
            /** @description Лимиты, которых в месяце ещё нет, копируются из месяца from */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetMonthDto"];
                };
            };
        };
    };
    RecurringController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description По возрастанию nextDate, законченные — в конце */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringPaymentDto"][];
                };
            };
        };
    };
    RecurringController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRecurringPaymentDto"];
            };
        };
        responses: {
            /** @description Повтор с тем же id возвращает уже созданный платёж */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringPaymentDto"];
                };
            };
            /** @description Неверные счёт, категория или суммы */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description id занят другим пользователем */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RecurringController_replace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveRecurringPaymentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringPaymentDto"];
                };
            };
            /** @description Неверные счёт, категория или суммы */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RecurringController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RecurringController_pay: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PayRecurringPaymentDto"];
            };
        };
        responses: {
            /** @description Создаёт операцию и сдвигает nextDate. Повтор с тем же transactionId возвращает тот же результат */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaidRecurringPaymentDto"];
                };
            };
            /** @description Повторение уже проведено или пропущено */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RecurringController_skip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkipRecurringPaymentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringPaymentDto"];
                };
            };
            /** @description Повторение уже проведено или пропущено */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GoalsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalDto"][];
                };
            };
        };
    };
    GoalsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGoalDto"];
            };
        };
        responses: {
            /** @description Повтор с тем же id возвращает уже созданную цель */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalDto"];
                };
            };
            /** @description id занят */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GoalsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GoalsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateGoalDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalDto"];
                };
            };
        };
    };
    NotificationsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationsDto"];
                };
            };
        };
    };
    NotificationsController_updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNotificationSettingsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationsDto"];
                };
            };
        };
    };
    NotificationsController_startLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ссылка на VK ID; действует 10 минут */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VkLinkUrlDto"];
                };
            };
            /** @description VK ID не настроен */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotificationsController_completeLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteVkLinkDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationsDto"];
                };
            };
            /** @description Ссылка устарела или код неверный */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Аккаунт ВК привязан к другому пользователю */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotificationsController_unlink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotificationsController_sendTest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Сообщение отправлено */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description ВК не привязан или сообщения запрещены */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
